import type { NextPage } from "next";
import Head from "next/head";
import ViewPage from "../components/pages/ViewPage";
import { getAllCards } from "../services";

// @ts-ignore
const View: NextPage = ({ cards }) => {
  return (
    <div>
      <Head>
        <title>Smash Cards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ViewPage cards={cards} />
      </main>
    </div>
  );
};

export async function getStaticProps() {
  const allCards = await getAllCards();

  return {
    props: { cards: allCards }, // will be passed to the page component as props
  };
}

export default View;
