import type { NextPage } from "next";
import Head from "next/head";
import ViewPage from "../components/pages/ViewPage";

const View: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Smash Cards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ViewPage />
      </main>
    </div>
  );
};

export default View;
